### ISSUE TITLE
请教：你是如何把[[page]]在github转换为[page](link-to-page)的？

### ISSUE THREAD

**Issue by makerjackie** [xiaoland/vscode_foam_chinese_document#1]
我看到这个文档都能够直接点击跳转，是程序自动转换的吗？

**Comment by makerjackie** [comment]
写了一个中文的快速入门，https://github.com/Jackiexiao/10-minutes-to-foam

**Comment by xiaoland** [comment]
markdown格式的文件都可以通过如下格式进行各种跳转：
文档：【显示出来的名字】（文件的路径）
网址：【显示出来的名字】（网址）
图片：！【显示出来的名字】（图片网址）
因为这个回复也是markdown，所以请把中文符号换成对应的英文符号即可

**Comment by xiaoland** [comment]
当然，你也可以直接查看我写的文件的源码，这样就很明显了

**Comment by xiaoland** [comment]
所以，我并没有使用Foam的[[]]这个导航功能，只是markdown纯粹的功能而已

**Comment by xiaoland** [comment]
谢谢你能把我的文档链接到你的快速入门中，我也会的

**Comment by xiaoland** [comment]
我再看了一遍问题，我好像会错意了，真是非常抱歉。
不过我确实没有使用Foam的[[page]]，就单纯的是markdown文档的跳转

**Comment by makerjackie** [comment]
因为我想分享自己的foam笔记到某个网页上, 不需要经过任何修改, 就可以通过点击[[page]]跳转到对应的页面

**Comment by hikerpig** [comment]
@Jackiexiao 可以使用 Foam 团队的 Jekyll 模板，是在前端使用 JS 替换的， 代码在此 [foam.html](https://github.com/hikerpig/foam/blob/master/docs/_layouts/foam.html)，自己单独起笔记项目的话参考一下 `docs` 目录组成。我看了一下 foambubble/foam-template 并没有更新这些内容，可能发布功能还在快速发展中。
@xiaoland  我感觉比较好的翻译工程组织应该是 fork 一份 foam 的主项目，保留原来的英文 docs 目录，`git mv docs docs_en`。 这样一来能够时刻同步和 diff 主 repo 的变化，易于译文的迭代。二来易于沿用 jekyll 模板和样式，发布的时候展示效果能与原 repo 保持统一。

**Comment by xiaoland** [comment]
> @Jackiexiao 可以使用 Foam 团队的 Jekyll 模板，是在前端使用 JS 替换的， 代码在此 [foam.html](https://github.com/hikerpig/foam/blob/master/docs/_layouts/foam.html)，自己单独起笔记项目的话参考一下 `docs` 目录组成。我看了一下 foambubble/foam-template 并没有更新这些内容，可能发布功能还在快速发展中。
> @xiaoland 我感觉比较好的翻译工程组织应该是 fork 一份 foam 的主项目，保留原来的英文 docs 目录，`git mv docs docs_en`。 这样一来能够时刻同步和 diff 主 repo 的变化，易于译文的迭代。二来易于沿用 jekyll 模板和样式，发布的时候展示效果能与原 repo 保持统一。

谢谢你的建议~！（不过这个项目好像已经没救了呢）

**Comment by hikerpig** [comment]
@Jackiexiao 我自己折腾了一个可以独立使用 Jekyll 部署的模板 https://hikerpig.github.io/foam-jekyll-template/ 。
目前 Jekyll 无法识别 `[[wiki link]]`，foam vscode 应该是通过自动插入底下这样不显示的片段来 hack 的。

```
[//begin]: # "Autogenerated link references for markdown compatibility"
[inbox]: inbox "Inbox"
[foam-tips]: foam-tips "Foam tips"
[//end]: # "Autogenerated link references"
```

**Comment by Jackiexiao** [comment]
> @Jackiexiao 我自己折腾了一个可以独立使用 Jekyll 部署的模板 https://hikerpig.github.io/foam-jekyll-template/ 。
> 目前 Jekyll 无法识别 `[[wiki link]]`，foam vscode 应该是通过自动插入底下这样不显示的片段来 hack 的。
> 
> ```
> [//begin]: # "Autogenerated link references for markdown compatibility"
> [inbox]: inbox "Inbox"
> [foam-tips]: foam-tips "Foam tips"
> [//end]: # "Autogenerated link references"
> ```

好咧，我晚点试一下，我最近也在断断续续折腾中，不过还没成功：https://github.com/Jackiexiao/blog

**Comment by makerjackie** [comment]
@hikerpig 好咧，我晚点试一下，我最近也在断断续续折腾中，不过还没成功：https://github.com/Jackiexiao/blog

**Comment by makerjackie** [comment]
> @Jackiexiao 我自己折腾了一个可以独立使用 Jekyll 部署的模板 https://hikerpig.github.io/foam-jekyll-template/ 。
> 目前 Jekyll 无法识别 `[[wiki link]]`，foam vscode 应该是通过自动插入底下这样不显示的片段来 hack 的。
> 
> ```
> [//begin]: # "Autogenerated link references for markdown compatibility"
> [inbox]: inbox "Inbox"
> [foam-tips]: foam-tips "Foam tips"
> [//end]: # "Autogenerated link references"
> ```

vscode:下面需要运行`Foam: Update Markdown Reference List`生成这个不显示的片段

这里有个坑 文件的第一个标题跟文件名要是一致的(比如`foam-tips.md`对应`# Foam Tips`), 否则无法自动生成对应关系...

**Comment by makerjackie** [comment]
还遇到一个图片的问题, 我看foam的官方文档里头是 `![Demo of graph visualiser](assets/images/foam-navigation-demo.gif)`

放在`assets/images/`这个文件夹下, 我的是在其他文件夹, 不知道foam的代码有没处理. 看来发布一个foam的知识库还真挺麻烦

**Comment by hikerpig** [comment]
> 还遇到一个图片的问题, 我看foam的官方文档里头是 `![Demo of graph visualiser](assets/images/foam-navigation-demo.gif)`
> 
> 放在`assets/images/`这个文件夹下, 我的是在其他文件夹, 不知道foam的代码有没处理. 看来发布一个foam的知识库还真挺麻烦

@Jackiexiao  是的，自己折腾的话是需要你对 Jekyll 有一点了解的，下面仅供参考
- https://jekyllrb.com/docs/static-files/
- https://docs.github.com/en/github/working-with-github-pages/about-github-pages-and-jekyll#about-jekyll

**Comment by makerjackie** [comment]
等之后有刚需再回来学习Jekyll，感谢。现在用你的这个模板足够分享foam的文字知识库了 https://hikerpig.github.io/foam-jekyll-template/
